export enum NotificationType {
    ADMIN = 'ADMIN',
    REQUEST_SUBMITTED = 'REQUEST_SUBMITTED',
    REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
    REQUEST_DRIVER_IN_ROUTE = 'REQUEST_DRIVER_IN_ROUTE',
    REQUEST_DRIVER_NEARBY = 'REQUEST_DRIVER_NEARBY',
    REQUEST_DOME = 'REQUEST_DOME',
    REQUEST_ASSIGNED = 'REQUEST_ASSIGNED',
    SILENT = 'SILENT'
}