export enum NotificationType {
    ADMIN = 'ADMIN',
    REQUEST_SUBMITTED = 'REQUEST_SUBMITTED',
    REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
    REQUEST_DRIVER_IN_ROUTE = 'REQUEST_DRIVER_IN_ROUTE',
    REQUEST_DRIVER_NEARBY = 'REQUEST_DRIVER_NEARBY',
    REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS',
    REQUEST_DONE = 'REQUEST_DONE',
    REQUEST_ASSIGNED = 'REQUEST_ASSIGNED',
    SILENT = 'SILENT',
    CHAT_MESSAGE = 'REQUEST_ASSIGNED',
    GLOBAL_NOTIFICATION = 'GLOBAL_NOTIFICATION',
    ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
}