export enum RequestStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  IN_ROUTE = 'IN_ROUTE',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  FIVE_MINUTES = 'FIVE_MINUTES',
}
